### ISSUE TITLE
Solución por si WebHooks no sale

### ISSUE THREAD

**Issue by edertxodw** [Sagardotegi/kupelike-symfony#8]
En el caso de que no consigamos conectar con [WebHooks de Facebook](https://developers.facebook.com/docs/graph-api/webhooks), buscar una **optativa desde nuestro servidor** que cada segundo haga llamadas a **Facebook** para obtener los datos.

@zmwebdev

**Comment by zmwebdev** [comment]
https://developers.facebook.com/docs/graph-api/webhooks
